---
title: "Pivot Lobsters"
author: "James Bourke"
date: "1/27/2020"
output: html_document
---

Attaching our packages and reading in data
```{r}
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages("skimr")
library(kableExtra) #install.packages("kableExtra")

# read in lobster data
lobsters <- read_xlsx(here("data", "lobsters.xlsx"),
                      skip = 4)

```

Viewing our data with skimr
```{r}
#these are equivalent
skimr::skim(lobsters) # explicitly stated from skimr
skim(lobsters) # not explicit
```

# Pivot Tables
In R, Pivot Tables are: `group_by() %>% summarize()`
`n()` function will count observations

```{r}
# group by year
lobsters %>%
  group_by(year) %>% 
  summarize(count_by_year = n())

# group by year and site
lobsters %>%
  group_by(year, site) %>% 
  summarize(count_by_year_site = n())

# group by site and year
lobsters %>%
  group_by(site, year) %>% 
  summarize(count_by_site_year = n())
```

Summarize by multiple variables
And assign as an object
```{r}
siteyear_summary <- lobsters %>% 
  group_by(site, year) %>% 
  summarize(count_by_site_year = n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_mm = sd(size_mm, na.rm = TRUE))
```

Table formatting with `kableExtra::kable()`
```{r}
siteyear_summary %>% 
  kable()
```

There are `r nrow(lobsters)` total lobsters included in this report.


